chore(actions): work on building and publishing the docker image
chore(devcontainer): added pwsh and oh-my-posh

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -3,11 +3,11 @@ name: Publish Release
 on: # yamllint disable-line rule:truthy
   workflow_dispatch:
     inputs:
-      force_next_version:
+      force-next-version:
         description: 'Force the next version. Must be in the format vX.Y.Z. Tag must not exist.'
         required: false
         default: ''
-      vsix_publish:
+      vsix-publish:
         description: 'Whether to publish the VSIX to the marketplaces.'
         required: false
         default: 'true'
@@ -52,7 +52,7 @@ jobs:
           enable_pr_comment: true
           token: ${{ github.token }}
         env:
-          FORCE_NEXT_VERSION: ${{ github.event.inputs.force_next_version || '' }}
+          FORCE_NEXT_VERSION: ${{ github.event.inputs.force-next-version || '' }}
       - run: |
           echo "next version: ${TAG}"
         env:
@@ -253,27 +253,133 @@ jobs:
           github-token: ${{ github.token }}
           codecov-token: ${{ secrets.CODECOV_TOKEN }}
 
-  extension:
+  vsix-package:
     runs-on: ubuntu-latest
-    environment: production
     needs:
+      - version
       - verify
       - test
       - lint
     permissions:
+      deployments: write
       contents: read
-      statuses: write
-      issues: write
-      pull-requests: write
+    outputs:
+      artifact-id: ${{ steps.package-vsix.outputs.artifact-id }}
+      artifact-url: ${{ steps.package-vsix.outputs.artifact-url }}
+      artifact-digest: ${{ steps.package-vsix.outputs.artifact-digest }}
     steps:
       - uses: actions/checkout@v6
         with:
-          persist-credentials: true
           fetch-depth: 0
+          persist-credentials: false
 
-      - uses: ./.github/actions/extension
+      - name: "Package VSIX"
+        uses: ./.github/actions/vsix/package
+        id: package-vsix
         with:
           github-token: ${{ github.token }}
-          version: ${{ needs.version.outputs.current_version }}
-          vsix_publish: ${{ github.event.inputs.vsix_publish }}
+          version: ${{ env.VERSION }}
+          package-owner: ${{ env.PACKAGE_OWNER }}
+          package-name: ${{ env.PACKAGE_NAME }}
 
+      - name: "VSIX Package Information"
+        shell: bash
+        run: |
+          {
+            echo "## Artifact Information"
+            echo ""
+            echo "| Artifact ID | Artifact URL | Artifact Digest |"
+            echo "|-------------|-------------|----------------|"
+            echo "| $ARTIFACT_ID | $ARTIFACT_URL | $ARTIFACT_DIGEST |"
+            echo ""
+          } >> "$GITHUB_STEP_SUMMARY"
+        env:
+          ARTIFACT_ID: ${{ steps.package-vsix.outputs.artifact-id }}
+          ARTIFACT_URL: ${{ steps.package-vsix.outputs.artifact-url }}
+          ARTIFACT_DIGEST: ${{ steps.package-vsix.outputs.artifact-digest }}
+
+  vsix-publish:
+    runs-on: ubuntu-latest
+    needs: vsix-package
+    permissions:
+      deployments: write
+      contents: read
+    steps:
+      - uses: actions/checkout@v6
+        with:
+          fetch-depth: 0
+          persist-credentials: false
+
+      - name: "Publish VSIX"
+        uses: ./.github/actions/vsix/publish
+        with:
+          github-token: ${{ github.token }}
+          artifact-name: ${{ needs.vsix-package.outputs.artifact-name }}
+          artifact-pattern: '*.vsix'
+          dry-run: ${{ env.ACT != '' || env.DRY_RUN == 'true' }}
+          vsix-publish: ${{ github.event.inputs.vsix-publish }}
+          vs-marketplace-token: ${{ secrets.VS_MARKETPLACE_TOKEN }}
+          openvsx-token: ${{ secrets.OPEN_VSX_TOKEN }}
+          version: ${{ steps.get.outputs.major_minor_patch }}
+          package-owner: ${{ env.PACKAGE_OWNER }}
+          package-name: ${{ env.PACKAGE_NAME }}
+
+  docker-publish:
+    if: ${{ github.event.inputs.docker-publish == 'true' }}
+    runs-on: ubuntu-latest
+    needs:
+      - vsix-package
+      - version
+    permissions:
+      deployments: write
+      contents: read
+    steps:
+      - uses: actions/checkout@v6
+        with:
+          fetch-depth: 0
+          persist-credentials: false
+
+      - name: "Lookup git-cliff Version for Build Args"
+        id: git-cliff
+        run: |
+          GIT_CLIFF_TAG=$(curl -s "https://api.github.com/repos/orhun/git-cliff/releases/latest" | jq -r ".tag_name")
+          GIT_CLIFF_VERSION=${GIT_CLIFF_TAG#v}
+          GIT_CLIFF_VERSION_SIG_URL="https://github.com/orhun/git-cliff/releases/download/$GIT_CLIFF_TAG/git-cliff-$GIT_CLIFF_VERSION-aarch64-unknown-linux-gnu.tar.gz.sha512"
+          # Verify the URL is valid
+          if curl --head --silent --fail "$GIT_CLIFF_VERSION_SIG_URL" >/dev/null; then
+            echo "GIT_CLIFF_VERSION=$GIT_CLIFF_VERSION" >> "$GITHUB_ENV"
+            echo "version=$GIT_CLIFF_VERSION" >> "$GITHUB_OUTPUT"
+          else
+            echo "Failed to fetch git-cliff version from GitHub API or the signature URL is not valid." >&2
+            exit 1
+          fi
+
+      - name: "Publish Docker Image"
+        uses: ./.github/actions/docker/publish
+        with:
+          github-token: ${{ github.token }}
+
+        env:
+          # Environment Variables
+          #   Support for multiple registries to push via Environment Variables
+          #   IDENTIFIER is a unique identifier for the variable group
+          #   - DBPA_USERNAME_IDENTIFIER=myuser
+          #   - DBPA_PASSWORD_IDENTIFIER=mypassword
+          #   - DBPA_REGISTRY_IDENTIFIER=myregistry.io
+          #
+          #   Build Args via Environment Variables
+          #   IDENTIFIER is the key of the build argument
+          #   - BUILD_ARGS_IDENTIFIER=mybuildarg
+          #   - BUILD_ARGS_ANOTHER_IDENTIFIER=myotherbuildarg
+          #
+          #   Labels via Environment Variables
+          #   IDENTIFIER is the key of the label
+          #   - LABELS_IDENTIFIER=mylabel
+
+          DBPA_USERNAME_GHCR: ${{ github.actor }}
+          DBPA_PASSWORD_GHCR: ${{ secrets.GITHUB_TOKEN }}
+          DBPA_REGISTRY_GHCR: ghcr.io
+
+          BUILD_ARGS_VERSION: ${{ steps.get.outputs.major_minor_patch }}
+          BUILD_ARGS_NODE_VERSION: '25'
+          BUILD_ARGS_GIT_CLIFF_VERSION: ${{ steps.git-cliff.outputs.version }}
